#!/usr/bin/env bash

# - Associative array used as a cache to mark which flag families have already
#   been compiled and validated.
# - Key: family name (string prefix).
# - Value: "1" if the family has been successfully compiled; absent or empty otherwise.
# - Prevents redundant reprocessing of the same flag family during a session.
declare -A SHELL_CLI_FLAG_COMPILED_FAMILY=()


# - Global variable that stores the last error message generated by
#   'shell_cli_compile_flag' or 'shell_cli_compile_flag_family'.
# - Cleared at the start of each compilation attempt.
# - On failure, contains a descriptive message indicating the flag or property
#   that caused the error.
# - Used as the single source of truth for reporting compilation errors.
declare -g SHELL_CLI_FLAG_COMPILE_ERR_MESSAGE=""
